#Configuration of the backend

#System port to run out of 
server.port=8080 
#can be changed later

#Application name
spring.application.name=firmhealth-backend

#show detailed error messages during development if false, else simplify
server.error.whitelabel.enabled=false

#swagger ui location
springdoc.swagger-ui.path=/swagger-ui.html
firmhealth.c-engine.path=../math_engine/ratios

firmhealth.r-analytics.url=http://localhost:8001
firmhealth.python-service.url=http://localhost:5000